[package]
name    = "json-order-service"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web
axum         = { version = "0.7", features = ["macros"] }
axum-extra   = { version = "0.9", features = ["cookie", "typed-header"] }
tokio        = { version = "1", features = ["full", "macros", "rt-multi-thread"] }
tower-http   = { version = "0.5", features = ["cors", "trace"] }

# Database — Neon DB (wajib TLS)
sqlx = { version = "0.8", features = [
    "runtime-tokio-native-tls", "postgres",
    "uuid", "chrono", "macros", "json"
] }

# Query builder
sea-query = { version = "0.32.0", features = [
    "backend-postgres",
    "with-uuid",
    "with-chrono",
    "with-json",
] }
sea-query-binder = { version = "0.7", features = [
    "sqlx-postgres",
    "with-uuid",
    "with-chrono",
    "with-json"
] }

# Swagger / OpenAPI
utoipa            = { version = "4", features = ["axum_extras","uuid","chrono"] }
#utoipa-swagger-ui = { version = "8", features = ["axum"] }
utoipa-scalar = { version = "0.1", features = ["axum"] }

# Serialisasi
serde      = { version = "1", features = ["derive"] }
serde_json = "1"

# Utilities
uuid        = { version = "1", features = ["serde","v4"] }
chrono      = { version = "0.4", features = ["serde"] }
dotenvy     = "0.15"
thiserror   = "1"
tracing     = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Auth
jsonwebtoken = "8"
argon2       = "0.5.3"

# Validasi
validator = { version = "0.18", features = ["derive"] }
repo = "0.14.6"

# Client Request
reqwest = { version = "0.12", features = ["json"] }
wiremock = "0.6.5"
base64 = "0.22.1"
async-trait = "0.1.89"
mockall = "0.14.0"
temp-env = "0.3.6"


[dev-dependencies]
# Srialisasi
serial_test = "3"
axum-test = "15"
wiremock = "0.6"
temp-env = { version = "0.3", features = ["async_closure"] }
