sonar.projectKey=advprog-2026-B18-project_json-order-service
sonar.organization=advprog-2026-b18-project
sonar.projectName=JSON Order Service
sonar.projectVersion=0.1.0
sonar.language=rust
sonar.coverage.jacoco.xmlReportPaths=coverage/cobertura.xml

sonar.sources=src
sonar.exclusions=**/target/**,**/migrations/**
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true

sonar.rust.clippy.reportPaths=clippy-report.json