# ─────────────────────────────────────────────
# SonarQube / SonarCloud project configuration
# Docs: https://docs.sonarsource.com/sonarqube
# ─────────────────────────────────────────────

sonar.projectKey=advprog-2026-B18-project_json-order-service
sonar.organization=advprog-2026-b18-project
sonar.projectName=JSON Order Service
sonar.projectVersion=0.1.0

# Source
sonar.sources=src
sonar.exclusions=**/target/**,**/migrations/**

# Coverage (dihasilkan oleh cargo-tarpaulin)
sonar.coverageReportPaths=coverage/cobertura.xml

# Language
sonar.language=rust

# Encoding
sonar.sourceEncoding=UTF-8

# Quality Gate — gagalkan pipeline jika tidak lolos
sonar.qualitygate.wait=true

sonar.rust.clippy.reportPaths=clippy-report.json
sonar.coverageReportPaths=coverage/lcov.info