name: Deploy Rust Axum App - Order Service
on:
  push:
    branches: 
      - main
      - setup/deploy

env:
  SERVICE_NAME: order-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/advprog-2026-b18-project/json-order-service:latest

      # Dynamically generate the .env file on the GitHub Runner
      - name: Generate .env file
        env:
          DB_URL: ${{ secrets.DB_URL_ORDER }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          INTERNAL_KEY: ${{ secrets.INTERNAL_SERVICE_KEY }}
          SERVICE_URL_INVENTORY: ${{ secrets.SERVICE_URL_INVENTORY }}
          SERVICE_URL_AUTH: ${{ secrets.SERVICE_URL_AUTH }}
          SERVICE_URL_PAYMENT: ${{ secrets.SERVICE_URL_PAYMENT }}
          AMQP_URL: ${{ secrets.AMQP_URL }}
        run: |
          echo "DATABASE_URL=$DB_URL" >> .env
          echo "JWT_SECRET=$JWT_SECRET" >> .env
          echo "INTERNAL_SERVICE_KEY=$INTERNAL_KEY" >> .env
          echo "INVENTORY_SERVICE_URL=$SERVICE_URL_INVENTORY" >> .env
          echo "USER_SERVICE_URL=$SERVICE_URL_AUTH" >> .env
          echo "WALLET_SERVICE_URL=$SERVICE_URL_PAYMENT" >> .env
          echo "AMQP_URL=${secrets.AMQP_URL}" >> .env
      
      # Copy docker-compose.yml and the newly generated .env via scp
      - name: Copy files via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml,.env" 
          target: "/home/ubuntu/"

      # Deploy on EC2 
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/advprog-2026-b18-project/json-order-service:latest
            docker compose -f /home/ubuntu/docker-compose.yml up -d --no-deps --build ${{ env.SERVICE_NAME }}
            chmod 600 /home/ubuntu/.env
            docker image prune -af